### ISSUE TITLE
"All X are Y" fails to parse

### ISSUE THREAD

**Issue by jarble** [Attempto/APE#20]
For example: "Every woman is a person" is a sentence that can be parsed by APE, but "All women are people" is not parsed at all.

**Comment by Kaljurand** [comment]
This is behavior by design. Namely, in ACE every noun must be preceded by a determiner (_every_, _some_, _all_, ...) to avoid a common class of English ambiguities.

```
All women are some people.

[]
   [A]
   object(A,woman,countable,na,eq,1)-1/2
   =>
   [B,C]
   object(B,people,mass,na,na,na)-1/5
   predicate(C,be,A,B)-1/3
```

See also: http://attempto.ifi.uzh.ch/site/docs/ace_troubleshooting.html
