### ISSUE TITLE
Unable to Compile on macOS

### ISSUE THREAD

**Issue by greg-gelfond** [Attempto/APE#38]
Hello, I'm attempting to get started with Attempto but am running into issues with getting the project to build from source. On running the command:

`bash make_exe.sh`

I have the following output:

```
Looking for command 'swipl'...
Reading "sorts.fit"
Reading "grammar.fit"
Reading "grammar_functionwords.fit"
Reading "grammar_contentwords.fit"
Writing "sorts.plp"
Writing "grammar.plp"
Writing "grammar_functionwords.plp"
Writing "grammar_contentwords.plp"
Warning: /Users/gregory/Downloads/ape-6.7-131003/utils/drs_to_html.pl:38:
Warning:    Deprecated declaration has no effect: style_check(atom)
ERROR: -g qsave_program('ape.exe', [goal(ape), toplevel(halt), local(25000), global(50000)]).: Domain error: `save_option' expected, found `local'
The command 'swipl' did not work. Let's try 'pl'...
pl {-input <file>} {-output <file>}
	Reads ASCII PL from stdin (or file if -input specified)
	and writes ASCII PL to stdout (or file if -output)
	NOTE: binary serialization is no longer supported
pl {-input <file>} {-output <file>}
	Reads ASCII PL from stdin (or file if -input specified)
	and writes ASCII PL to stdout (or file if -output)
	NOTE: binary serialization is no longer supported
Error: SWI Prolog not found
```

This is somewhat odd however, since I do have SWI-Prolog installed via `homebrew`, and it's in my path:

```
swipl --version
SWI-Prolog version 9.0.4 for arm64-darwin
```

I'm not quite sure how to proceed at this point and any tips or suggestions would be appreciated.

**Comment by Kaljurand** [comment]
There were some updates to the build script 5 years ago. Also, `make_exe.sh` was removed then (in https://github.com/Attempto/APE/commit/00fb91d476a90b665b392ed042e464c76df5db76).

Can you try the latest version?

**Comment by greg-gelfond** [comment]
That seemed to work. I was then able to copy the compiled executable to `/opt/local/bin` and run it from there as well so I seem to be good to go.
